# This hook depends on helm creating the target namespace if it doesn't exist
# before the hook is called. This is the case on Helm v2.9.1
apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-ns-{{ .Release.Namespace }}
  namespace: kube-system
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: annotator
        image: gcr.io/google_containers/hyperkube:v1.13.10
        command:
        - kubectl
        - annotate
        - --overwrite
        - namespace
        - {{ .Release.Namespace }}
        - "iam.amazonaws.com/permitted=.*"
      restartPolicy: Never
      # use tiller service account since it should have permissions to do namespace labeling
      serviceAccountName: tiller
