# This hook depends on helm creating the target namespace if it doesn't exist
# before the hook is called. This is the case on Helm v2
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-annotator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ns-annotator
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ns-annotator
subjects:
  - kind: ServiceAccount
    name: ns-annotator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-annotator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-ns-{{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: annotator
        image: gcr.io/google_containers/hyperkube:v1.13.10
        command:
        - kubectl
        - annotate
        - --overwrite
        - namespace
        - {{ .Release.Namespace }}
        - "iam.amazonaws.com/permitted=.*"
      - name: labeler
        image: gcr.io/google_containers/hyperkube:v1.13.10
        command:
        - kubectl
        - label
        - namespace
        - --overwrite
        - {{ .Release.Namespace }}
        - istio-injection=enabled
      restartPolicy: Never
      serviceAccountName: ns-annotator
